// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDK4ZovZczTbVanrIcAJHmRStlZNErqRMs',
    appId: '1:512365624933:android:237d6f8f763f8968e8108c',
    messagingSenderId: '512365624933',
    projectId: 'hukum-98b72',
    databaseURL: 'https://hukum-98b72-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'hukum-98b72.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrHvhnS3Wo4maIDritc34hr6vYeScOCDs',
    appId: '1:512365624933:ios:bda4359cbff5ea39e8108c',
    messagingSenderId: '512365624933',
    projectId: 'hukum-98b72',
    databaseURL: 'https://hukum-98b72-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'hukum-98b72.firebasestorage.app',
    iosBundleId: 'com.hukum.hukumApp',
  );
}
